### ISSUE TITLE
LICENSE for re-using?

### ISSUE THREAD

**Issue by pfisterer** [fvsch/outdent-string#1]
Hi @fvsch, I was wondering whether I can use your code in a project of mine (https://github.com/pfisterer/reveal-template) as you've published no license. Tanks, Dennis

**Comment by fvsch** [comment]
Hi @pfisterer. I added a license (MIT, should be compatible with your project).
It's old code that was never used outside of a demo, but feel free to use it if you find it useful!

**Comment by pfisterer** [comment]
Great, thanks a million. It was exactly what I needed.

**Comment by fvsch** [comment]
@pfisterer Heads up that I rewrote the repo's history a bit:

- Changed `master` branch to `main`
- Changed my name in commits (they were using my old first name ^^)
- Removed a text file (it's online at https://fvsch.com/articles/outdent-js/article.txt)

The `outdent.js` file itself didn't change.

So if you have this repo checked out, pulling will fail.

**Comment by pfisterer** [comment]
Thanks. I basically copied the file to https://github.com/pfisterer/reveal-template/blob/master/plugins/outdent.js and changed `function removeExtraIndentation(text, options) {` to `export default function removeExtraIndentation(text, options) {` to be able to `import`the function.
